# Generated by Django 6.1 on 2026-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_collegeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='category',
            field=models.CharField(blank=True, help_text='User can enter any category (e.g., Engineering, Medical, Arts, etc.)', max_length=255, null=True),
        ),
    ]
