# Generated by Django 6.1 on 2026-09-04 10:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_college_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number of the college', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Mark college as recommended (manual)'),
        ),
        migrations.AddField(
            model_name='college',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='College logo image', max_length=255, null=True, verbose_name='logo'),
        ),
    ]
