# Generated by Django 6.1 on 2026-09-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_college_contact_number_college_is_recommended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate of the college', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate of the college', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='user_id',
            field=models.CharField(blank=True, help_text="User ID(s) associated with the college (e.g., ['1','2','3'])", max_length=255, null=True),
        ),
    ]
