# Generated by Django 6.1 on 2026-09-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_college_latitude_college_longitude_college_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='user_id',
        ),
    ]
