# Generated by Django 6.1 on 2026-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_remove_college_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='booking',
            field=models.JSONField(blank=True, default=list, help_text="List of bookings: [{'user_id': '1', 'booking': True}, ...]"),
        ),
    ]
