# Generated by Django 6.1 on 2026-09-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_college_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='booking',
            field=models.BooleanField(default=False, help_text='True if any user has booked this college'),
        ),
    ]
