# Generated by Django 6.1 on 2026-09-13 20:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_remove_college_booking_college_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='category',
            field=models.CharField(blank=True, help_text='User can enter any category (e.g., Engineering, Medical, Arts, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number of the college', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Mark college as recommended (manual)'),
        ),
        migrations.AlterField(
            model_name='college',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate of the college', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='College logo image', max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='college',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate of the college', max_digits=9, null=True),
        ),
    ]
