# Generated by Django 6.1 on 2026-08-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_teacher_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
