# Generated by Django 6.1 on 2026-09-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_auth_user',
        ),
    ]
