# Generated by Django 6.1 on 2026-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentleave',
            name='student_id',
        ),
        migrations.AddField(
            model_name='studentleave',
            name='school_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentleave',
            name='student_class',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
