# Generated by Django 6.1 on 2026-09-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_leave', '0002_remove_studentleave_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentleave',
            name='apply_status',
        ),
    ]
