# Generated by Django 6.1 on 2026-09-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_leave', '0003_remove_studentleave_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='leave_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='teacher_card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
