# Generated by Django 6.1 on 2026-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngocategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
