# Generated by Django 6.1 on 2026-10-06 13:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_ngocategory_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ngocategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_ngo_category_name_ci'),
        ),
    ]
