# Generated by Django 6.1 on 2026-08-18 19:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_profile', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_profile')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('adhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('SSSMID', models.CharField(blank=True, max_length=50, null=True)),
                ('student_class', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('caste_category', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_status', models.CharField(blank=True, max_length=50, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('check_box', models.BooleanField(default=False)),
                ('school_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
