# Generated by Django 6.1 on 2026-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id_card',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
