# Generated by Django 6.1 on 2026-08-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id_card',
        ),
    ]
