# Generated by Django 6.1 on 2026-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_student_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id_card',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
