# Generated by Django 6.1 on 2026-09-11 16:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_horizontal', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail_horizontal')),
                ('thumbnail_vertical', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail_vertical')),
                ('content_type', models.CharField(default='webseries', editable=False, max_length=50)),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='webseries.webseries')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('webseries', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_horizontal', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='episode_thumbnail_horizontal')),
                ('thumbnail_vertical', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='episode_thumbnail_vertical')),
                ('duration', models.CharField(help_text='e.g., 45m', max_length=50)),
                ('video_url', models.URLField(max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='webseries.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
