# Generated by Django 6.1 on 2026-09-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries',
            name='duration',
            field=models.CharField(default='', help_text='e.g., 2h 15m or 45m', max_length=50),
            preserve_default=False,
        ),
    ]
