# Generated by Django 6.1 on 2026-09-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webseries', '0002_webseries_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='webseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='webseries.webseries'),
        ),
    ]
