# Generated by Django 6.1 on 2026-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField(help_text='ID of the college being booked')),
                ('user_id', models.CharField(help_text='User ID who is booking the college', max_length=255)),
                ('booking', models.BooleanField(default=True, help_text='Booking status (True = booked)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
