# Generated by Django 6.1 on 2026-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegebooking',
            name='message',
            field=models.TextField(blank=True, help_text='Message to send to the college on WhatsApp when booking is created', null=True),
        ),
    ]
