# Generated by Django 6.1 on 2026-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_booking', '0002_collegebooking_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegebooking',
            name='room_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the room (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='room_id',
            field=models.IntegerField(blank=True, help_text='ID of the room (optional)', null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='room_name',
            field=models.CharField(blank=True, help_text='Name of the room (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='room_type',
            field=models.CharField(blank=True, help_text='Type of the room (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='tiffin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the tiffin (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='tiffin_id',
            field=models.IntegerField(blank=True, help_text='ID of the tiffin (optional)', null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='tiffin_name',
            field=models.CharField(blank=True, help_text='Name of the tiffin (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collegebooking',
            name='tiffin_type',
            field=models.CharField(blank=True, help_text='Type of the tiffin (optional)', max_length=100, null=True),
        ),
    ]
