# Generated by Django 6.1 on 2026-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_booking', '0003_collegebooking_room_amount_collegebooking_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegebooking',
            name='room_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='tiffin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='tiffin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='tiffin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collegebooking',
            name='tiffin_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
