# Generated by Django 6.1 on 2026-09-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave'), ('LATE', 'Late'), ('WEEK_OFF', 'Week Off')], default='PRESENT', max_length=20),
        ),
    ]
