# Generated by Django 6.1 on 2026-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student_ids',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student_names',
        ),
        migrations.AddField(
            model_name='homework',
            name='student_ids_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
