# Generated by Django 6.1 on 2026-10-06 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_ngocategory_unique_ngo_category_name_ci'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='category.ngocategory'),
        ),
    ]
