# Generated by Django 6.1 on 2026-10-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_ngoservice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoservice',
            name='image',
        ),
        migrations.AddField(
            model_name='ngoservice',
            name='choose_amount',
            field=models.JSONField(blank=True, default=list, help_text='List of quick-select donation amounts'),
        ),
        migrations.AddField(
            model_name='ngoservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoservice',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs'),
        ),
        migrations.AddField(
            model_name='ngoservice',
            name='keys',
            field=models.JSONField(blank=True, default=list, help_text='List of key-value items'),
        ),
        migrations.AddField(
            model_name='ngoservice',
            name='progress',
            field=models.JSONField(blank=True, default=dict, help_text='Progress info: target_amount, total_amount, donor'),
        ),
    ]
