# Generated by Django 6.1 on 2026-09-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextrasalary',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherpendingsalary',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachersalaryrequest',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='teachersalary',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='TeacherBankDetail',
        ),
        migrations.DeleteModel(
            name='TeacherExtraSalary',
        ),
        migrations.DeleteModel(
            name='TeacherPendingSalary',
        ),
        migrations.DeleteModel(
            name='TeacherSalaryRequest',
        ),
    ]
