# Generated by Django 6.1 on 2026-10-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_remove_ngoservice_image_ngoservice_choose_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField(blank=True, db_index=True, help_text='User/Donor ID from your auth system', null=True)),
                ('donate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_image', models.URLField(blank=True, null=True)),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='service.ngoservice')),
            ],
            options={
                'verbose_name': 'NGO History',
                'verbose_name_plural': 'NGO History',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['donor_id', '-created_at'], name='history_ngo_donor_i_7f0476_idx'), models.Index(fields=['service', '-created_at'], name='history_ngo_service_70f9ee_idx')],
            },
        ),
    ]
