# Generated by Django 6.1 on 2026-10-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngohistory',
            name='note',
        ),
    ]
