# Generated by Django 6.1 on 2026-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Important', 'Important'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('audience', models.CharField(choices=[('Students', 'Students'), ('Parents', 'Parents'), ('Both', 'Both'), ('Staff', 'Staff')], default='Students', max_length=20)),
                ('assigned_class', models.CharField(default='All Classes', max_length=100)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
