# Generated by Django 6.1 on 2026-09-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='send_push',
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
    ]
