# Generated by Django 6.1 on 2026-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_remove_notice_is_scheduled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='status',
        ),
    ]
