# Generated by Django 6.1 on 2026-09-27 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_remove_notice_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
    ]
