# Generated by Django 6.1 on 2026-09-02 19:30

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiffin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_nonveg', models.BooleanField(default=False)),
                ('is_booking', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Rating out of 5', max_digits=3)),
                ('near_college', models.CharField(blank=True, help_text='Nearby college name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TiffinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tiffin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiffin_images', to='tiffin.tiffin')),
            ],
        ),
    ]
