# Generated by Django 6.1 on 2026-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for tiffin orders', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='is_nonveg',
            field=models.CharField(blank=True, help_text='User can enter any non-veg type (e.g., Chicken, Mutton, Fish, Egg, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='is_veg',
            field=models.CharField(blank=True, help_text='User can enter any veg type (e.g., Pure Veg, Veg, Jain Veg, etc.)', max_length=255, null=True),
        ),
    ]
