# Generated by Django 6.1 on 2026-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0002_tiffin_contact_number_alter_tiffin_is_nonveg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
