# Generated by Django 6.1 on 2026-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffin', '0003_tiffin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiffin',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Latitude coordinate of the tiffin location', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiffin',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Longitude coordinate of the tiffin location', max_digits=9),
            preserve_default=False,
        ),
    ]
