# Generated by Django 6.1 on 2026-09-28 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=50)),
                ('exam_type', models.CharField(choices=[('board', 'Board Exam'), ('halfYearly', 'Half Yearly'), ('annual', 'Annual Exam'), ('preBoard', 'Pre-Board'), ('unitTest', 'Unit Test')], db_index=True, max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_timetables_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_timetables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Class Exam Timetable',
                'verbose_name_plural': 'Class Exam Timetables',
                'ordering': ['-from_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('invigilator', models.CharField(max_length=120)),
                ('room', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.classexamtimetable')),
            ],
            options={
                'verbose_name': 'Subject Schedule',
                'verbose_name_plural': 'Subject Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
