# Generated by Django 6.1 on 2026-09-28 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classexamtimetable',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='classexamtimetable',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
