# Generated by Django 6.1 on 2026-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_classexamtimetable_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classexamtimetable',
            name='created_by',
        ),
        migrations.AddField(
            model_name='classexamtimetable',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
