# Generated by Django 6.1 on 2026-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_classexamtimetable_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classexamtimetable',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
