# Generated by Django 6.1 on 2026-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_classexamtimetable_created_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexamtimetable',
            name='created_by_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
