# Generated by Django 6.1 on 2026-09-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['-created_at']},
        ),
    ]
