# Generated by Django 6.1 on 2026-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=100)),
                ('admin_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary'), ('college', 'College'), ('university', 'University')], max_length=50)),
                ('class_name', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('student_marks', models.IntegerField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('remark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_card',
            },
        ),
    ]
