# Generated by Django 6.1 on 2026-09-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='pasingmaks_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student_id',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportcard',
            name='sujectmaks_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
