# Generated by Django 6.1 on 2026-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0002_remove_reportcard_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='school_type',
            field=models.CharField(max_length=50),
        ),
    ]
