# Generated by Django 6.1 on 2026-09-01 09:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(blank=True, max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_number', models.CharField(max_length=20)),
                ('driver_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='driver_image')),
                ('students_data', models.JSONField(blank=True, default=list, help_text='List of students with their details')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('route_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['-created_at'],
            },
        ),
    ]
