# Generated by Django 6.1 on 2026-09-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='students_data',
        ),
    ]
