# Generated by Django 6.1 on 2026-09-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transport_students_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='is_active',
        ),
    ]
