# Generated by Django 6.1 on 2026-09-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_remove_transport_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=50)),
                ('pickup_time', models.CharField(blank=True, max_length=50, null=True)),
                ('drop_time', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='transport.transport')),
            ],
            options={
                'verbose_name': 'Transport Student',
                'verbose_name_plural': 'Transport Students',
                'ordering': ['student_name'],
                'unique_together': {('transport', 'student_id')},
            },
        ),
    ]
