# Generated by Django 6.1 on 2026-09-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transportstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportstudent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
