# Generated by Django 6.1 on 2026-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_student_student_id_card'),
        ('teacher', '0003_remove_teacher_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('team', 'Team')], max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_staff', models.ManyToManyField(blank=True, related_name='meetings', to='teacher.teacher')),
                ('selected_students', models.ManyToManyField(blank=True, related_name='meetings', to='student.student')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
