# Generated by Django 6.1 on 2026-09-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='selected_staff',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='selected_students',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='team_name',
        ),
        migrations.AddField(
            model_name='meeting',
            name='for_meeting',
            field=models.CharField(default='Student', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='zoom_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
