# Generated by Django 6.1 on 2026-08-25 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_student_student_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_card', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_pass', to='student.student')),
            ],
            options={
                'db_table': 'student_pass',
                'ordering': ['-created_at'],
            },
        ),
    ]
