# Generated by Django 6.1 on 2026-09-21 11:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('teacher_id_card', models.CharField(max_length=100)),
                ('apply_status', models.BooleanField(default=True)),
                ('reason_msg', models.TextField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='teacher_leave')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teacher_leave',
                'ordering': ['-created_date'],
            },
        ),
    ]
