# Generated by Django 6.1 on 2026-09-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0001_initial'),
        ('content', '0001_initial'),
        ('sci_fi', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cartoon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_entry', to='cartoons.cartoon'),
        ),
        migrations.AddField(
            model_name='content',
            name='sci_fi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_entry', to='sci_fi.scifi'),
        ),
        migrations.AddField(
            model_name='content',
            name='sport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_entry', to='sports.sport'),
        ),
    ]
