# Generated by Django 6.1 on 2026-09-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_cartoon_content_sci_fi_content_sport'),
        ('webseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='webseries',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_entry', to='webseries.webseries'),
        ),
    ]
