# Generated by Django 6.1 on 2026-09-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_id',
        ),
    ]
