# Generated by Django 6.1 on 2026-09-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, help_text='User can enter any room type (e.g., 1BHK, 2BHK, Studio, Penthouse, etc.)', max_length=255, null=True),
        ),
    ]
