# Generated by Django 6.1 on 2026-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_add_user_id_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate of the room location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate of the room location', max_digits=9, null=True),
        ),
    ]
