# Generated by Django 6.1 on 2026-09-02 19:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_near_college_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
