# Generated by Django 6.1 on 2026-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for room inquiries', max_length=20, null=True),
        ),
    ]
