# Generated by Django 6.1 on 2026-08-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_teacher_teacher_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id_card', models.CharField(db_index=True, max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_pass', to='teacher.teacher')),
            ],
            options={
                'db_table': 'teacher_pass',
                'ordering': ['-created_at'],
            },
        ),
    ]
