# Generated by Django 6.1 on 2026-10-08 00:04

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('it_service_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItServiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('old_price', models.CharField(blank=True, default='', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('rating', models.FloatField(default=4.5)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('color_hex', models.CharField(blank=True, default='', help_text='Optional hex like #3B82F6 for card accent color', max_length=10)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='["Flutter","Firebase","Node.js"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='it_service_category.itservicecategory')),
            ],
            options={
                'db_table': 'it_service_service',
                'ordering': ['-id'],
            },
        ),
    ]
