# Generated by Django 6.1 on 2026-10-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_service_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itserviceservice',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='itserviceservice',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='itserviceservice',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='itserviceservice',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='itserviceservice',
            name='reviews',
        ),
    ]
