# Generated by Django 6.1 on 2026-09-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='student_att_year_267a19_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
