# Generated by Django 6.1 on 2026-09-09 21:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_horizontal', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail_horizontal')),
                ('thumbnail_vertical', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail_vertical')),
                ('content_type', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('language', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('video_url', models.URLField(max_length=500)),
                ('rating', models.CharField(max_length=20)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
