# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS rating numeric(3,1) NOT NULL DEFAULT 0.0;
            """,
            reverse_sql="""
                ALTER TABLE movies_movie 
                DROP COLUMN IF EXISTS rating;
            """,
        ),
    ]