# Generated by Django 6.1 on 2026-09-09 20:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail_horijental',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_horizontal',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail_horizontal'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_vertical',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail_vertical'),
        ),
    ]
