# Generated by Django 6.1 on 2026-09-09 20:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_horijental',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='thumbnail_horijental'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_vertical',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='thumbnail_vertical'),
        ),
    ]
