# Generated by Django 6.1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_rating_to_movie'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS is_trending boolean NOT NULL DEFAULT false;
                
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS is_recommended boolean NOT NULL DEFAULT false;
                
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
                
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now();
                
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();
                
                ALTER TABLE movies_movie 
                ADD COLUMN IF NOT EXISTS content_type varchar(50) NOT NULL DEFAULT 'movie';
            """,
            reverse_sql="""
                ALTER TABLE movies_movie DROP COLUMN IF EXISTS is_trending;
                ALTER TABLE movies_movie DROP COLUMN IF EXISTS is_recommended;
                ALTER TABLE movies_movie DROP COLUMN IF EXISTS is_active;
                ALTER TABLE movies_movie DROP COLUMN IF EXISTS created_at;
                ALTER TABLE movies_movie DROP COLUMN IF EXISTS updated_at;
                ALTER TABLE movies_movie DROP COLUMN IF EXISTS content_type;
            """,
        ),
    ]